### ISSUE TITLE
whisper_result_to_srt incorrectly rounds start/end time to integers

### ISSUE THREAD

**Issue by j-b-m** [peterk/srt_equalizer#2]
Hi and thanks for this utiliy.
There is a problem in whisper_result_to_srt, as segments start/end are rounded to integer values, while the original values can be like "3.8999999999999995". This causes unwanted moves of the subtitles.
https://github.com/peterk/srt_equalizer/blob/8972b568227a440bef68f3ecd8bf67ddb231e240/src/srt_equalizer/srt_equalizer.py#L26

**Comment by peterk** [comment]
Hi! Thx fir the report. I was under the impression that Whisper only produced integer timestamps (see https://github.com/openai/whisper/discussions/809) but will have a look.
